site_name: MKDocs for Beginners
repo_url: https://github.com/Fedozie/MkDocs-Project.git/
nav: 
  - Home: 'index.html'
  - 'Getting Started': 'gettingStarted.md'
  - 'User Guide': 'userGuide.md'
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    scheme: slate
    primary: teal
    accent: cyan
  font:
    text: "Roboto"
  code:
    font: "Roboto Mono"



