site_name: MKDocs for Beginners
repo_url: https://github.com/Fedozie/MkDocs-Project.git/
nav: 
  - Home: 'index.html'
  - 'Getting Started': 'gettingStarted.md'
  - 'User Guide': 'userGuide.md'
theme: cinder

